// SPDX-License-Identifier: GPL-2.0-or-later
//
// Visual effects: a click-through layer on top of everything, a textured
// particle system, sigils, shockwaves, screen flashes, floating labels and
// a helper for frame-by-frame animations.
//
// The textures in assets/ are generated by tools/make-textures.js.
// Small particles come pre-coloured (the nearest baked colour is picked);
// big white sprites (sigil, vortex, shockwave) are tinted on the fly.

import Clutter from 'gi://Clutter';
import Cogl from 'gi://Cogl';
import Gio from 'gi://Gio';
import GLib from 'gi://GLib';
import Graphene from 'gi://Graphene';
import St from 'gi://St';

import * as Main from 'resource:///org/gnome/shell/ui/main.js';

const MAX_PARTICLES = 260;

// How much bigger the texture box is than the bright part of the particle.
const BOX = {orb: 3, sparkle: 4.5, smoke: 1.6, flame: 1.5, snow: 1.6};
const VARIANTS = {smoke: 3, flame: 4, snow: 2};

export const rand = (a, b) => a + (b - a) * Math.random();

export function rgba([r, g, b], a = 1) {
    return `rgba(${Math.round(r * 255)}, ${Math.round(g * 255)}, ${Math.round(b * 255)}, ${a})`;
}

export function mix(c1, c2, t) {
    return [0, 1, 2].map(i => c1[i] + (c2[i] - c1[i]) * t);
}

export function monitorAt(x, y) {
    const monitors = Main.layoutManager.monitors;
    return monitors.find(m => x >= m.x && x < m.x + m.width && y >= m.y && y < m.y + m.height) ??
        Main.layoutManager.primaryMonitor ?? monitors[0];
}

export function pointerMonitor() {
    const [x, y] = global.get_pointer();
    return monitorAt(x, y);
}

export const Palette = {
    fire: [[1, 0.45, 0.08], [1, 0.72, 0.2], [1, 0.93, 0.6], [0.92, 0.22, 0.05]],
    frost: [[0.65, 0.88, 1], [0.88, 0.96, 1], [1, 1, 1]],
    sparkle: [[1, 0.85, 0.4], [1, 0.55, 0.88], [1, 1, 1], [0.68, 0.5, 1]],
    smoke: [[0.55, 0.45, 0.7], [0.45, 0.4, 0.55], [0.65, 0.6, 0.75]],
    dream: [[0.75, 0.7, 1], [0.55, 0.65, 1], [1, 0.85, 0.4]],
};

/** A callback that destroys the actor unless it is already gone. */
export function destroyer(actor) {
    let dead = false;
    actor.connect('destroy', () => (dead = true));
    return () => {
        if (!dead)
            actor.destroy();
    };
}

export const pick = list => list[Math.floor(Math.random() * list.length)];

function cogl([r, g, b], a = 1) {
    return new Cogl.Color({red: Math.round(r * 255), green: Math.round(g * 255), blue: Math.round(b * 255), alpha: Math.round(a * 255)});
}

export class Fx {
    /**
     * @param {Gio.Settings} settings
     * @param {string} extPath extension folder (for assets/)
     */
    constructor(settings, extPath) {
        this._settings = settings;
        this._count = 0;
        this._timeouts = new Set();
        this._assets = GLib.build_filenamev([extPath, 'assets']);
        this._uris = new Map();
        try {
            const [, bytes] = GLib.file_get_contents(GLib.build_filenamev([this._assets, 'manifest.json']));
            this._colors = Object.entries(JSON.parse(new TextDecoder().decode(bytes)).colors);
        } catch (e) {
            console.error(`Spellcaster: missing assets/manifest.json: ${e}`);
            this._colors = [['white', [1, 1, 1]]];
        }

        this.layer = new St.Widget({name: 'spellcasterFxLayer', reactive: false, x: 0, y: 0});
        this.layer.add_constraint(new Clutter.BindConstraint({
            source: global.stage,
            coordinate: Clutter.BindCoordinate.SIZE,
        }));
        Main.layoutManager.uiGroup.add_child(this.layer);
    }

    /** 0.25 with "reduce effects" on, 1 otherwise. */
    get amount() {
        return this._settings.get_boolean('reduce-effects') ? 0.25 : 1;
    }

    /** Keep the layer above anything added after us (menus, etc). */
    raise() {
        this.layer.get_parent()?.set_child_above_sibling(this.layer, null);
    }

    add(actor) {
        this.raise();
        this.layer.add_child(actor);
        return actor;
    }

    later(ms, fn) {
        const id = GLib.timeout_add(GLib.PRIORITY_DEFAULT, ms, () => {
            this._timeouts.delete(id);
            fn();
            return GLib.SOURCE_REMOVE;
        });
        this._timeouts.add(id);
        return id;
    }

    cancelLater(id) {
        if (id && this._timeouts.delete(id))
            GLib.source_remove(id);
    }

    // --- Textures ----------------------------------------------------------

    _uri(name) {
        let uri = this._uris.get(name);
        if (!uri) {
            uri = Gio.File.new_for_path(GLib.build_filenamev([this._assets, `${name}.png`])).get_uri();
            this._uris.set(name, uri);
        }
        return uri;
    }

    _nearestColor(c) {
        let best = this._colors[0][0], bd = Infinity;
        for (const [name, v] of this._colors) {
            const d = (v[0] - c[0]) ** 2 + (v[1] - c[1]) ** 2 + (v[2] - c[2]) ** 2;
            if (d < bd) {
                bd = d;
                best = name;
            }
        }
        return best;
    }

    textureFor(kind, color) {
        if (kind === 'orb' || kind === 'sparkle')
            return `${kind}-${this._nearestColor(color ?? [1, 1, 1])}`;
        return `${kind}-${Math.floor(Math.random() * (VARIANTS[kind] ?? 1))}`;
    }

    /**
     * A textured sprite actor centred on (x, y).
     * opts: texture, x, y, size (or width/height), tint [r,g,b], opacity,
     *       rotation, parent
     */
    sprite(opts) {
        const w = opts.width ?? opts.size, h = opts.height ?? opts.size;
        const a = new St.Widget({
            style: `background-image: url("${this._uri(opts.texture)}"); background-size: ${Math.ceil(w)}px ${Math.ceil(h)}px;`,
            width: Math.ceil(w),
            height: Math.ceil(h),
            x: Math.round(opts.x - w / 2),
            y: Math.round(opts.y - h / 2),
            opacity: Math.round(255 * (opts.opacity ?? 1)),
            rotation_angle_z: opts.rotation ?? 0,
            pivot_point: new Graphene.Point({x: 0.5, y: 0.5}),
            reactive: false,
        });
        if (opts.tint)
            a.add_effect(new Clutter.ColorizeEffect({tint: cogl(opts.tint)}));
        (opts.parent ?? this.layer).add_child(a);
        return a;
    }

    /**
     * One particle.
     * opts: kind ('orb'|'sparkle'|'smoke'|'flame'|'snow'), x, y, dx, dy,
     *       size (size of the bright part), color, alpha, duration, delay,
     *       endScale, startScale, spin (degrees), mode, parent
     */
    particle(opts) {
        if (this._count >= MAX_PARTICLES)
            return null;
        const kind = opts.kind ?? 'orb';
        const box = (opts.size ?? 6) * (BOX[kind] ?? 3);
        const p = this.sprite({
            texture: this.textureFor(kind, opts.color),
            x: opts.x,
            y: opts.y,
            size: box,
            opacity: opts.alpha ?? 1,
            rotation: opts.rotation ?? (kind === 'orb' ? 0 : rand(0, 360)),
            parent: opts.parent,
        });
        if (opts.startScale !== undefined)
            p.set_scale(opts.startScale, opts.startScale);
        this._count++;
        p.connect('destroy', () => this._count--);
        const done = destroyer(p);
        const duration = opts.duration ?? 600;
        const delay = opts.delay ?? 0;
        // Fly out with one curve, fade with another: bright most of the way.
        p.ease({
            x: p.x + (opts.dx ?? 0),
            y: p.y + (opts.dy ?? 0),
            rotation_angle_z: p.rotation_angle_z + (opts.spin ?? 0),
            delay,
            duration,
            mode: opts.mode ?? Clutter.AnimationMode.EASE_OUT_QUAD,
        });
        p.ease({
            opacity: 0,
            scale_x: opts.endScale ?? 0.35,
            scale_y: opts.endScale ?? 0.35,
            delay,
            duration,
            mode: Clutter.AnimationMode.EASE_IN_QUAD,
            onStopped: done,
        });
        return p;
    }

    // --- Effect recipes ----------------------------------------------------

    /** Glowing orbs and twinkles flying outward from a point. */
    burst(x, y, {count = 24, colors = Palette.sparkle, speed = 120, size = [3, 8], duration = [450, 1000], up = 0, stars = 0.3} = {}) {
        this.raise();
        const n = Math.round(count * this.amount);
        for (let i = 0; i < n; i++) {
            const a = Math.random() * Math.PI * 2;
            const d = speed * rand(0.3, 1);
            const star = Math.random() < stars;
            this.particle({
                kind: star ? 'sparkle' : 'orb',
                x, y,
                dx: Math.cos(a) * d,
                dy: Math.sin(a) * d - up * rand(0.5, 1),
                size: rand(size[0], size[1]) * (star ? 1.3 : 1),
                color: pick(colors),
                spin: star ? rand(-180, 180) : 0,
                duration: rand(duration[0], duration[1]),
            });
        }
    }

    /** Embers and flame licks rising out of a rectangle (a burning window). */
    embers(rect, count = 80) {
        this.raise();
        const n = Math.round(count * this.amount);
        for (let i = 0; i < n; i++) {
            this.particle({
                x: rect.x + Math.random() * rect.width,
                y: rect.y + Math.random() * rect.height,
                dx: rand(-40, 40),
                dy: -rand(80, 260),
                size: rand(2.5, 6),
                color: pick(Palette.fire),
                delay: rand(0, 300),
                duration: rand(700, 1400),
            });
        }
        this.flames(rect, Math.round(count / 4));
    }

    /** Flame tongues licking up from the bottom of a rectangle. */
    flames(rect, count = 20) {
        this.raise();
        const n = Math.max(3, Math.round(count * this.amount));
        for (let i = 0; i < n; i++) {
            const size = rand(rect.width / 9, rect.width / 5);
            this.particle({
                kind: 'flame',
                x: rect.x + (i + Math.random()) / n * rect.width,
                y: rect.y + rect.height * rand(0.55, 1),
                dx: rand(-15, 15),
                dy: -rand(rect.height * 0.25, rect.height * 0.6),
                size,
                rotation: rand(-8, 8),
                startScale: 0.6,
                endScale: 1.2,
                alpha: 0.95,
                delay: rand(0, 350),
                duration: rand(650, 1100),
            });
        }
    }

    /** Soft puff of smoke (a fizzle, or after a fire). */
    smoke(x, y, count = 14, {tint = 'purple'} = {}) {
        this.raise();
        const n = Math.max(3, Math.round(count * this.amount));
        for (let i = 0; i < n; i++) {
            const p = this.particle({
                kind: 'smoke',
                x: x + rand(-12, 12),
                y: y + rand(-12, 12),
                dx: rand(-40, 40),
                dy: -rand(30, 90),
                size: rand(26, 46),
                alpha: rand(0.75, 1),
                startScale: 0.5,
                endScale: 1.8,
                spin: rand(-60, 60),
                duration: rand(900, 1500),
            });
            if (p && tint === 'purple')
                p.add_effect(new Clutter.ColorizeEffect({tint: cogl([0.6, 0.45, 0.85])}));
        }
    }

    /** Twinkling stars drifting down from the top of a monitor. */
    sparkleRain(monitor, count = 70) {
        this.raise();
        const n = Math.round(count * this.amount);
        for (let i = 0; i < n; i++) {
            const star = i % 3 !== 0;
            this.particle({
                kind: star ? 'sparkle' : 'orb',
                x: monitor.x + Math.random() * monitor.width,
                y: monitor.y - rand(0, 40),
                dx: rand(-60, 60),
                dy: monitor.height * rand(0.35, 0.9),
                size: star ? rand(4, 9) : rand(2, 5),
                color: pick(Palette.sparkle),
                spin: star ? rand(-240, 240) : 0,
                startScale: 1,
                endScale: 0.4,
                delay: rand(0, 1000),
                duration: rand(1800, 3000),
                mode: Clutter.AnimationMode.EASE_IN_OUT_SINE,
            });
        }
    }

    /** Snowflakes drifting down across a monitor. */
    snowfall(monitor, count = 40) {
        this.raise();
        const n = Math.round(count * this.amount);
        for (let i = 0; i < n; i++) {
            this.particle({
                kind: 'snow',
                x: monitor.x + Math.random() * monitor.width,
                y: monitor.y + rand(-40, monitor.height * 0.5),
                dx: rand(-40, 40),
                dy: rand(120, 320),
                size: rand(10, 26),
                alpha: rand(0.7, 1),
                spin: rand(-120, 120),
                startScale: 0.3,
                endScale: 1,
                delay: rand(0, 600),
                duration: rand(1300, 2200),
                mode: Clutter.AnimationMode.EASE_OUT_SINE,
            });
        }
    }

    /** An expanding ring of light. */
    shockwave(x, y, {color = [1, 1, 1], size = 300, duration = 650, delay = 0} = {}) {
        const s = this.sprite({texture: 'shockwave', x, y, size, tint: color, opacity: 0.95});
        s.set_scale(0.15, 0.15);
        s.ease({
            scale_x: 1, scale_y: 1, opacity: 0, delay, duration,
            mode: Clutter.AnimationMode.EASE_OUT_CUBIC,
            onStopped: destroyer(s),
        });
        return s;
    }

    /**
     * A glowing magic circle that spins in, holds, and fades.
     * Returns the container actor.
     */
    sigil(x, y, {colors = [[0.7, 0.42, 1], [1, 0.45, 0.85]], size = 320, hold = 350, spin = 120, parent = null} = {}) {
        const box = new St.Widget({
            width: size, height: size,
            x: Math.round(x - size / 2), y: Math.round(y - size / 2),
            pivot_point: new Graphene.Point({x: 0.5, y: 0.5}),
            reactive: false, opacity: 0,
        });
        (parent ?? this.layer).add_child(box);
        this.raise();
        this.sprite({texture: 'sigil-glow', x: size / 2, y: size / 2, size, tint: colors[0], parent: box});
        this.sprite({texture: 'sigil', x: size / 2, y: size / 2, size, tint: mix(colors[1], [1, 1, 1], 0.55), parent: box});
        box.set_scale(0.55, 0.55);
        box.rotation_angle_z = -spin * 0.4;
        const done = destroyer(box);
        box.ease({opacity: 255, scale_x: 1, scale_y: 1, duration: 260, mode: Clutter.AnimationMode.EASE_OUT_BACK});
        box.ease({
            rotation_angle_z: spin,
            duration: 260 + hold + 450,
            mode: Clutter.AnimationMode.EASE_OUT_QUAD,
        });
        this.later(260 + hold, () => box.ease({
            opacity: 0, scale_x: 1.25, scale_y: 1.25, duration: 450,
            mode: Clutter.AnimationMode.EASE_IN_QUAD, onStopped: done,
        }));
        return box;
    }

    /** Full-monitor colour flash. */
    flash(monitor, color = [1, 1, 1], peak = 0.6, duration = 260) {
        const f = this.add(new St.Widget({
            style: `background-color: ${rgba(color, 1)};`,
            x: monitor.x, y: monitor.y, width: monitor.width, height: monitor.height,
            opacity: Math.round(peak * 255),
            reactive: false,
        }));
        f.ease({opacity: 0, duration, mode: Clutter.AnimationMode.EASE_OUT_QUAD, onStopped: destroyer(f)});
        return f;
    }

    /** Floating text label that rises and fades. */
    label(text, x, y, {fizzle = false, duration = 1100} = {}) {
        const l = this.add(new St.Label({
            text,
            style_class: fizzle ? 'spellcaster-label-fizzle' : 'spellcaster-label',
            opacity: 0,
            reactive: false,
        }));
        const [, natW] = l.get_preferred_width(-1);
        const [, natH] = l.get_preferred_height(-1);
        l.set_position(Math.round(x - natW / 2), Math.round(y - natH / 2));
        const done = destroyer(l);
        l.ease({
            opacity: 255,
            duration: 150,
            mode: Clutter.AnimationMode.EASE_OUT_QUAD,
            onComplete: () => l.ease({
                y: l.y - 50,
                opacity: 0,
                delay: duration * 0.35,
                duration: duration * 0.65,
                mode: Clutter.AnimationMode.EASE_IN_QUAD,
                onStopped: done,
            }),
            onStopped: finished => {
                if (!finished)
                    done();
            },
        });
        return l;
    }

    /**
     * Frame-by-frame animation driven by the stage clock.
     * onFrame(progress 0..1) every frame, onDone() at the end.
     */
    animate(actor, duration, onFrame, onDone) {
        const tl = new Clutter.Timeline({actor, duration});
        tl.connect('new-frame', () => onFrame(tl.get_progress()));
        tl.connect('completed', () => {
            onFrame(1);
            onDone?.();
        });
        tl.start();
        return tl;
    }

    destroy() {
        for (const id of this._timeouts)
            GLib.source_remove(id);
        this._timeouts.clear();
        this.layer.destroy();
        this.layer = null;
    }
}
